ALTER TABLE "candidates" ADD COLUMN "fullName" TEXT;
ALTER TABLE "cvs" ADD COLUMN "isHidden" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "cvs" ADD COLUMN "isBuilder" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "cvs" ADD COLUMN "builderData" JSONB;
ALTER TABLE "cvs" ADD COLUMN "templateId" TEXT;
